SUBROUTINE WRITE_R2C_DATA(NML,NLTEST,NMTEST,NCOUNT,IMIN,ACLASS, &
                          NLAT,XXX,YYY,XCOUNT,YCOUNT,ILMOS,JLMOS,ILG, &
                          NR2C,NR2CFILES,R2CFILEUNITSTART,GRD,GAT, &
                          GRDGAT,NR2CSTATES,R2C_ATTRIBUTES,FRAME_NO,YY, &
                          MM,DD,HH,MI,IC,ICP1,IG, &
                       TBARGAT,THLQGAT,THICGAT,TPNDGAT,ZPNDGAT, &
                       TBASGAT,ALBSGAT,TSNOGAT,RHOSGAT,SNOGAT,  &
                       TCANGAT,RCANGAT,SCANGAT,GROGAT, CMAIGAT, &
                       FCANGAT,LNZ0GAT,ALVCGAT,ALICGAT,PAMXGAT, &
                       PAMNGAT,CMASGAT,ROOTGAT,RSMNGAT,QA50GAT, &
                       VPDAGAT,VPDBGAT,PSGAGAT,PSGBGAT,PAIDGAT, &
                       HGTDGAT,ACVDGAT,ACIDGAT,TSFSGAT,WSNOGAT, &
                       THPGAT, THRGAT, THMGAT, BIGAT,  PSISGAT, &
                       GRKSGAT,THRAGAT,HCPSGAT,TCSGAT,          &
                       THFCGAT,PSIWGAT,DLZWGAT,ZBTWGAT,         &
                       ZSNLGAT,ZPLGGAT,ZPLSGAT,TACGAT, QACGAT,  &
                       DRNGAT, XSLPGAT,XDGAT,WFSFGAT,KSGAT,     &
                       ALGWGAT,ALGDGAT,ASVDGAT,ASIDGAT,AGVDGAT, &
                       AGIDGAT,ISNDGAT,RADJGAT,ZBLDGAT,Z0ORGAT, &
                       ZRFMGAT,ZRFHGAT,ZDMGAT, ZDHGAT, FSVHGAT, &
                       FSIHGAT,CSZGAT, FDLGAT, ULGAT,  VLGAT,   &
                       TAGAT,  QAGAT,  PRESGAT,PREGAT, PADRGAT, &
                       VPDGAT, TADPGAT,RHOAGAT,RPCPGAT,TRPCGAT, &
                       SPCPGAT,TSPCGAT,RHSIGAT,FCLOGAT,DLONGAT, &
                       GGEOGAT,                                 &
                       CDHGAT, CDMGAT, HFSGAT, TFXGAT, QEVPGAT, &
                       QFSGAT, QFXGAT, PETGAT, GAGAT,  EFGAT,   &
                       GTGAT,  QGGAT,  ALVSGAT,ALIRGAT, &
                       SFCTGAT,SFCUGAT,SFCVGAT,SFCQGAT,FSNOGAT, &
                       FSGVGAT,FSGSGAT,FSGGGAT,FLGVGAT,FLGSGAT, &
                       FLGGGAT,HFSCGAT,HFSSGAT,HFSGGAT,HEVCGAT, &
                       HEVSGAT,HEVGGAT,HMFCGAT,HMFNGAT,HTCCGAT, &
                       HTCSGAT,PCFCGAT,PCLCGAT,PCPNGAT,PCPGGAT, &
                       QFGGAT, QFNGAT, QFCLGAT,QFCFGAT,ROFGAT,  &
                       ROFOGAT,ROFSGAT,ROFBGAT,TROFGAT,TROOGAT, &
                       TROSGAT,TROBGAT,ROFCGAT,ROFNGAT,ROVGGAT, &
                       WTRCGAT,WTRSGAT,WTRGGAT,DRGAT,  GFLXGAT, &
                       HMFGGAT,HTCGAT, QFCGAT,MANNGAT, DDGAT,   &
                       IGDRGAT,VMODGAT,QLWOGAT)

INTEGER      NR2C, NR2CFILES,FRAME_NO,YY,MM,DD,HH,MI
INTEGER      GRD(NR2C),GAT(NR2C),GRDGAT(NR2C)
CHARACTER(*) R2C_ATTRIBUTES(NR2C,3)

INTEGER NML,NLTEST,NMTEST,NCOUNT,IMIN,NLAT,ILG,XCOUNT,YCOUNT,IC,ICP1,IG
INTEGER XXX(NLAT),YYY(NLAT)
INTEGER ILMOS(ILG),JLMOS(ILG),IGDRGAT(ILG)

REAL ACLASS(NLTEST,NMTEST+1)
REAL DATAIN(ILG),DATAOUT(NR2CSTATES,XCOUNT,YCOUNT),DATAOUT2(XCOUNT,YCOUNT)

!     * LAND SURFACE PROGNOSTIC VARIABLES.
REAL    TBARGAT(ILG,IG),   THLQGAT(ILG,IG),   THICGAT(ILG,IG), &
        TPNDGAT(ILG),      ZPNDGAT(ILG),      TBASGAT(ILG),   &
        ALBSGAT(ILG),      TSNOGAT(ILG),      RHOSGAT(ILG),   &
        SNOGAT (ILG),      TCANGAT(ILG),      RCANGAT(ILG),   &
        SCANGAT(ILG),      GROGAT (ILG),      CMAIGAT(ILG), &
        TSFSGAT(ILG,4),    TACGAT (ILG),      QACGAT (ILG), &
        WSNOGAT(ILG)

!     * CANOPY AND SOIL INFORMATION ARRAYS.
!     * (THE LENGTH OF THESE ARRAYS IS DETERMINED BY THE NUMBER
!     * OF SOIL LAYERS (3) AND THE NUMBER OF BROAD VEGETATION
!     * CATEGORIES (4, OR 5 INCLUDING URBAN AREAS).)
!
REAL    FCANGAT(ILG,ICP1),   LNZ0GAT(ILG,ICP1), &
        ALVCGAT(ILG,ICP1),   ALICGAT(ILG,ICP1), &
        PAMXGAT(ILG,IC),     PAMNGAT(ILG,IC),   &
        CMASGAT(ILG,IC),     ROOTGAT(ILG,IC),   &
        RSMNGAT(ILG,IC),     QA50GAT(ILG,IC),   &
        VPDAGAT(ILG,IC),     VPDBGAT(ILG,IC),   &
        PSGAGAT(ILG,IC),     PSGBGAT(ILG,IC),   &
        PAIDGAT(ILG,IC),     HGTDGAT(ILG,IC),   &
        ACVDGAT(ILG,IC),     ACIDGAT(ILG,IC) 

REAL    THPGAT (ILG,IG),   THRGAT (ILG,IG),   THMGAT (ILG,IG), &
        BIGAT  (ILG,IG),   PSISGAT(ILG,IG),   GRKSGAT(ILG,IG), &   
        THRAGAT(ILG,IG),   HCPSGAT(ILG,IG),                    &
        TCSGAT (ILG,IG),   THFCGAT(ILG,IG),   PSIWGAT(ILG,IG), &
        DLZWGAT(ILG,IG),   ZBTWGAT(ILG,IG),                    &
        DRNGAT (ILG),      XSLPGAT(ILG),      XDGAT(ILG),      &
        WFSFGAT(ILG),      KSGAT(ILG),        ALGWGAT(ILG),    &   
        ALGDGAT(ILG),      ASVDGAT(ILG),      ASIDGAT(ILG),    &    
        AGVDGAT(ILG),      AGIDGAT(ILG),      ZSNLGAT(ILG),    &
        ZPLGGAT(ILG),      ZPLSGAT(ILG)

INTEGER ISNDGAT(ILG,IG)

!     * ATMOSPHERIC AND GRID-CONSTANT INPUT VARIABLES.
!
REAL    ZRFMGAT(ILG), ZRFHGAT(ILG), ZDMGAT (ILG), ZDHGAT (ILG), &
        FSVHGAT(ILG), FSIHGAT(ILG), CSZGAT (ILG), FDLGAT (ILG), &
        ULGAT  (ILG), VLGAT  (ILG), TAGAT  (ILG), QAGAT  (ILG), &
        PRESGAT(ILG), PREGAT (ILG), PADRGAT(ILG), VPDGAT (ILG), &
        TADPGAT(ILG), RHOAGAT(ILG), ZBLDGAT(ILG), Z0ORGAT(ILG), &
        RPCPGAT(ILG), TRPCGAT(ILG), SPCPGAT(ILG), TSPCGAT(ILG), &
        RHSIGAT(ILG), FCLOGAT(ILG), DLONGAT(ILG), GGEOGAT(ILG), &
        RADJGAT(ILG), VMODGAT(ILG), QLWOGAT(ILG)

!     * LAND SURFACE DIAGNOSTIC VARIABLES.

REAL    CDHGAT (ILG),  CDMGAT (ILG),  HFSGAT (ILG),  TFXGAT (ILG), &
        QEVPGAT(ILG),  QFSGAT (ILG),  QFXGAT (ILG),  PETGAT (ILG), &
        GAGAT  (ILG),  EFGAT  (ILG),  GTGAT  (ILG),  QGGAT  (ILG), &
        ALVSGAT(ILG),  ALIRGAT(ILG),  FSNOGAT(ILG), &
        SFCTGAT(ILG),  SFCUGAT(ILG),  SFCVGAT(ILG),  SFCQGAT(ILG), &
        FSGVGAT(ILG),  FSGSGAT(ILG),  FSGGGAT(ILG),  FLGVGAT(ILG), &
        FLGSGAT(ILG),  FLGGGAT(ILG),  HFSCGAT(ILG),  HFSSGAT(ILG), &
        HFSGGAT(ILG),  HEVCGAT(ILG),  HEVSGAT(ILG),  HEVGGAT(ILG), &
        HMFCGAT(ILG),  HMFNGAT(ILG),  HTCCGAT(ILG),  HTCSGAT(ILG), &
        PCFCGAT(ILG),  PCLCGAT(ILG),  PCPNGAT(ILG),  PCPGGAT(ILG), &
        QFGGAT (ILG),  QFNGAT (ILG),  QFCLGAT(ILG),  QFCFGAT(ILG), &
        ROFGAT (ILG),  ROFOGAT(ILG),  ROFSGAT(ILG),  ROFBGAT(ILG), &
        TROFGAT(ILG),  TROOGAT(ILG),  TROSGAT(ILG),  TROBGAT(ILG), &
        ROFCGAT(ILG),  ROFNGAT(ILG),  ROVGGAT(ILG),  WTRCGAT(ILG), &
        WTRSGAT(ILG),  WTRGGAT(ILG),  DRGAT  (ILG)

REAL    HMFGGAT(ILG,IG),  HTCGAT (ILG,IG),  QFCGAT (ILG,IG), &
        GFLXGAT(ILG,IG)
    
! * WATROF DECLARATIONS
REAL    DDGAT(ILG),MANNGAT(ILG)

!     * SAND AND CLAY
REAL    SANDGAT(ILG,IG),   CLAYGAT(ILG,IG)

INTEGER FILECOUNT,R2CFILEUNITSTART,R2CFILEUNIT,NR2CSTATES

!>COLLECT OUTPUT DATA
CALL R2C_DATA(DATAIN,DATAOUT,NML,NLTEST,NMTEST,NCOUNT, &
              IMIN,ACLASS,NR2C,GRD,GAT,GRDGAT,NR2CSTATES, &
              NLAT,XXX,YYY,XCOUNT,YCOUNT,ILMOS,JLMOS,ILG,IC,ICP1,IG, &
                       TBARGAT,THLQGAT,THICGAT,TPNDGAT,ZPNDGAT, &
                       TBASGAT,ALBSGAT,TSNOGAT,RHOSGAT,SNOGAT,  &
                       TCANGAT,RCANGAT,SCANGAT,GROGAT, CMAIGAT, &
                       FCANGAT,LNZ0GAT,ALVCGAT,ALICGAT,PAMXGAT, &
                       PAMNGAT,CMASGAT,ROOTGAT,RSMNGAT,QA50GAT, &
                       VPDAGAT,VPDBGAT,PSGAGAT,PSGBGAT,PAIDGAT, &
                       HGTDGAT,ACVDGAT,ACIDGAT,TSFSGAT,WSNOGAT, &
                       THPGAT, THRGAT, THMGAT, BIGAT,  PSISGAT, &
                       GRKSGAT,THRAGAT,HCPSGAT,TCSGAT,          &
                       THFCGAT,PSIWGAT,DLZWGAT,ZBTWGAT,         &
                       ZSNLGAT,ZPLGGAT,ZPLSGAT,TACGAT, QACGAT,  &
                       DRNGAT, XSLPGAT,XDGAT,WFSFGAT,KSGAT,     &
                       ALGWGAT,ALGDGAT,ASVDGAT,ASIDGAT,AGVDGAT, &
                       AGIDGAT,ISNDGAT,RADJGAT,ZBLDGAT,Z0ORGAT, &
                       ZRFMGAT,ZRFHGAT,ZDMGAT, ZDHGAT, FSVHGAT, &
                       FSIHGAT,CSZGAT, FDLGAT, ULGAT,  VLGAT,   &
                       TAGAT,  QAGAT,  PRESGAT,PREGAT, PADRGAT, &
                       VPDGAT, TADPGAT,RHOAGAT,RPCPGAT,TRPCGAT, &
                       SPCPGAT,TSPCGAT,RHSIGAT,FCLOGAT,DLONGAT, &
                       GGEOGAT,                                 &
                       CDHGAT, CDMGAT, HFSGAT, TFXGAT, QEVPGAT, &
                       QFSGAT, QFXGAT, PETGAT, GAGAT,  EFGAT,   &
                       GTGAT,  QGGAT,  ALVSGAT,ALIRGAT, &
                       SFCTGAT,SFCUGAT,SFCVGAT,SFCQGAT,FSNOGAT, &
                       FSGVGAT,FSGSGAT,FSGGGAT,FLGVGAT,FLGSGAT, &
                       FLGGGAT,HFSCGAT,HFSSGAT,HFSGGAT,HEVCGAT, &
                       HEVSGAT,HEVGGAT,HMFCGAT,HMFNGAT,HTCCGAT, &
                       HTCSGAT,PCFCGAT,PCLCGAT,PCPNGAT,PCPGGAT, &
                       QFGGAT, QFNGAT, QFCLGAT,QFCFGAT,ROFGAT,  &
                       ROFOGAT,ROFSGAT,ROFBGAT,TROFGAT,TROOGAT, &
                       TROSGAT,TROBGAT,ROFCGAT,ROFNGAT,ROVGGAT, &
                       WTRCGAT,WTRSGAT,WTRGGAT,DRGAT,  GFLXGAT, &
                       HMFGGAT,HTCGAT, QFCGAT,                  &
                       MANNGAT, DDGAT, SANDGAT,CLAYGAT,IGDRGAT, &
                       VMODGAT,QLWOGAT)

FILECOUNT = 0
R2CFILEUNIT = R2CFILEUNITSTART
DO N = 1, NR2C
   IF(GRD(N) == 1)THEN
      FILECOUNT = FILECOUNT + 1
      R2CFILEUNIT = R2CFILEUNIT + 1
      WRITE(R2CFILEUNIT,9000)':Frame',FRAME_NO,FRAME_NO,YY,MM,DD,HH,MI
      DO J = 1, YCOUNT
         WRITE(R2CFILEUNIT,'(999(F12.6))')(DATAOUT(FILECOUNT,I,J),I=1,XCOUNT)
      ENDDO
      WRITE(R2CFILEUNIT,'(A)')':EndFrame'
   ENDIF
   
   IF(GAT(N) == 1)THEN
      DO K = 1, NMTEST
         FILECOUNT = FILECOUNT + 1
         R2CFILEUNIT = R2CFILEUNIT + 1
         WRITE(R2CFILEUNIT,9000)':Frame',FRAME_NO,FRAME_NO,YY,MM,DD,HH,MI
         DO J = 1, YCOUNT
            WRITE(R2CFILEUNIT,'(999(F12.6))')(DATAOUT(FILECOUNT,I,J),I=1,XCOUNT)
         ENDDO
         WRITE(R2CFILEUNIT,'(A)')':EndFrame'
     ENDDO
   ENDIF
   
   IF(GRDGAT(N) == 1)THEN
      DO K = 1, NMTEST
         FILECOUNT = FILECOUNT + 1
         R2CFILEUNIT = R2CFILEUNIT + 1
         WRITE(R2CFILEUNIT,9000)':Frame',FRAME_NO,FRAME_NO,YY,MM,DD,HH,MI
         DO J = 1, YCOUNT
            WRITE(R2CFILEUNIT,'(999(F12.6))')(DATAOUT(FILECOUNT,I,J),I=1,XCOUNT)
         ENDDO
         WRITE(R2CFILEUNIT,'(A)')':EndFrame'
      ENDDO
   ENDIF
ENDDO

9000 FORMAT(A6,2I10,3X,'"',I4,'/',I2.2,'/',I2.2,1X,I2.2,':',I2.2,':00.000"')

RETURN
END