SUBROUTINE R2C_DATA(DATAIN,DATAOUT,NML,NLTEST,NMTEST,NCOUNT, &
                    IMIN,ACLASS,NR2C,GRD,GAT,GRDGAT,NR2CSTATES, &
                    NLAT,XXX,YYY,XCOUNT,YCOUNT,ILMOS,JLMOS,ILG,IC,ICP1,IG, &
                       TBARGAT,THLQGAT,THICGAT,TPNDGAT,ZPNDGAT, &
                       TBASGAT,ALBSGAT,TSNOGAT,RHOSGAT,SNOGAT,  &
                       TCANGAT,RCANGAT,SCANGAT,GROGAT, CMAIGAT, &
                       FCANGAT,LNZ0GAT,ALVCGAT,ALICGAT,PAMXGAT, &
                       PAMNGAT,CMASGAT,ROOTGAT,RSMNGAT,QA50GAT, &
                       VPDAGAT,VPDBGAT,PSGAGAT,PSGBGAT,PAIDGAT, &
                       HGTDGAT,ACVDGAT,ACIDGAT,TSFSGAT,WSNOGAT, &
                       THPGAT, THRGAT, THMGAT, BIGAT,  PSISGAT, &
                       GRKSGAT,THRAGAT,HCPSGAT,TCSGAT,          &
                       THFCGAT,PSIWGAT,DLZWGAT,ZBTWGAT,         &
                       ZSNLGAT,ZPLGGAT,ZPLSGAT,TACGAT, QACGAT,  &
                       DRNGAT, XSLPGAT,XDGAT,WFSFGAT,KSGAT,     &
                       ALGWGAT,ALGDGAT,ASVDGAT,ASIDGAT,AGVDGAT, &
                       AGIDGAT,ISNDGAT,RADJGAT,ZBLDGAT,Z0ORGAT, &
                       ZRFMGAT,ZRFHGAT,ZDMGAT, ZDHGAT, FSVHGAT, &
                       FSIHGAT,CSZGAT, FDLGAT, ULGAT,  VLGAT,   &
                       TAGAT,  QAGAT,  PRESGAT,PREGAT, PADRGAT, &
                       VPDGAT, TADPGAT,RHOAGAT,RPCPGAT,TRPCGAT, &
                       SPCPGAT,TSPCGAT,RHSIGAT,FCLOGAT,DLONGAT, &
                       GGEOGAT,                                 &
                       CDHGAT, CDMGAT, HFSGAT, TFXGAT, QEVPGAT, &
                       QFSGAT, QFXGAT, PETGAT, GAGAT,  EFGAT,   &
                       GTGAT,  QGGAT,  ALVSGAT,ALIRGAT, &
                       SFCTGAT,SFCUGAT,SFCVGAT,SFCQGAT,FSNOGAT, &
                       FSGVGAT,FSGSGAT,FSGGGAT,FLGVGAT,FLGSGAT, &
                       FLGGGAT,HFSCGAT,HFSSGAT,HFSGGAT,HEVCGAT, &
                       HEVSGAT,HEVGGAT,HMFCGAT,HMFNGAT,HTCCGAT, &
                       HTCSGAT,PCFCGAT,PCLCGAT,PCPNGAT,PCPGGAT, &
                       QFGGAT, QFNGAT, QFCLGAT,QFCFGAT,ROFGAT,  &
                       ROFOGAT,ROFSGAT,ROFBGAT,TROFGAT,TROOGAT, &
                       TROSGAT,TROBGAT,ROFCGAT,ROFNGAT,ROVGGAT, &
                       WTRCGAT,WTRSGAT,WTRGGAT,DRGAT,  GFLXGAT, &
                       HMFGGAT,HTCGAT, QFCGAT,                  &
                       MANNGAT,DDGAT,  SANDGAT, CLAYGAT,IGDRGAT,&
                       VMODGAT,QLWOGAT)
 
!     * LAND SURFACE PROGNOSTIC VARIABLES.
REAL    TBARGAT(ILG,IG),   THLQGAT(ILG,IG),   THICGAT(ILG,IG), &
        TPNDGAT(ILG),      ZPNDGAT(ILG),      TBASGAT(ILG),   &
        ALBSGAT(ILG),      TSNOGAT(ILG),      RHOSGAT(ILG),   &
        SNOGAT (ILG),      TCANGAT(ILG),      RCANGAT(ILG),   &
        SCANGAT(ILG),      GROGAT (ILG),      CMAIGAT(ILG), &
        TSFSGAT(ILG,4),    TACGAT (ILG),      QACGAT (ILG), &
        WSNOGAT(ILG)

!     * CANOPY AND SOIL INFORMATION ARRAYS.
!     * (THE LENGTH OF THESE ARRAYS IS DETERMINED BY THE NUMBER
!     * OF SOIL LAYERS (3) AND THE NUMBER OF BROAD VEGETATION
!     * CATEGORIES (4, OR 5 INCLUDING URBAN AREAS).)
!
REAL    FCANGAT(ILG,ICP1),   LNZ0GAT(ILG,ICP1), &
        ALVCGAT(ILG,ICP1),   ALICGAT(ILG,ICP1), &
        PAMXGAT(ILG,IC),     PAMNGAT(ILG,IC),   &
        CMASGAT(ILG,IC),     ROOTGAT(ILG,IC),   &
        RSMNGAT(ILG,IC),     QA50GAT(ILG,IC),   &
        VPDAGAT(ILG,IC),     VPDBGAT(ILG,IC),   &
        PSGAGAT(ILG,IC),     PSGBGAT(ILG,IC),   &
        PAIDGAT(ILG,IC),     HGTDGAT(ILG,IC),   &
        ACVDGAT(ILG,IC),     ACIDGAT(ILG,IC) 

REAL    THPGAT (ILG,IG),   THRGAT (ILG,IG),   THMGAT (ILG,IG), &
        BIGAT  (ILG,IG),   PSISGAT(ILG,IG),   GRKSGAT(ILG,IG), &   
        THRAGAT(ILG,IG),   HCPSGAT(ILG,IG),                    &
        TCSGAT (ILG,IG),   THFCGAT(ILG,IG),   PSIWGAT(ILG,IG), &
        DLZWGAT(ILG,IG),   ZBTWGAT(ILG,IG),                    &
        DRNGAT (ILG),      XSLPGAT(ILG),      XDGAT(ILG),      &
        WFSFGAT(ILG),      KSGAT(ILG),        ALGWGAT(ILG),    &   
        ALGDGAT(ILG),      ASVDGAT(ILG),      ASIDGAT(ILG),    &    
        AGVDGAT(ILG),      AGIDGAT(ILG),      ZSNLGAT(ILG),    &
        ZPLGGAT(ILG),      ZPLSGAT(ILG)

INTEGER ISNDGAT(ILG,IG)

!     * ATMOSPHERIC AND GRID-CONSTANT INPUT VARIABLES.
!
REAL    ZRFMGAT(ILG), ZRFHGAT(ILG), ZDMGAT (ILG), ZDHGAT (ILG), &
        FSVHGAT(ILG), FSIHGAT(ILG), CSZGAT (ILG), FDLGAT (ILG), &
        ULGAT  (ILG), VLGAT  (ILG), TAGAT  (ILG), QAGAT  (ILG), &
        PRESGAT(ILG), PREGAT (ILG), PADRGAT(ILG), VPDGAT (ILG), &
        TADPGAT(ILG), RHOAGAT(ILG), ZBLDGAT(ILG), Z0ORGAT(ILG), &
        RPCPGAT(ILG), TRPCGAT(ILG), SPCPGAT(ILG), TSPCGAT(ILG), &
        RHSIGAT(ILG), FCLOGAT(ILG), DLONGAT(ILG), GGEOGAT(ILG), &
        RADJGAT(ILG), VMODGAT(ILG), QLWOGAT(ILG)

!     * LAND SURFACE DIAGNOSTIC VARIABLES.

REAL    CDHGAT (ILG),  CDMGAT (ILG),  HFSGAT (ILG),  TFXGAT (ILG), &
        QEVPGAT(ILG),  QFSGAT (ILG),  QFXGAT (ILG),  PETGAT (ILG), &
        GAGAT  (ILG),  EFGAT  (ILG),  GTGAT  (ILG),  QGGAT  (ILG), &
        ALVSGAT(ILG),  ALIRGAT(ILG),  FSNOGAT(ILG), &
        SFCTGAT(ILG),  SFCUGAT(ILG),  SFCVGAT(ILG),  SFCQGAT(ILG), &
        FSGVGAT(ILG),  FSGSGAT(ILG),  FSGGGAT(ILG),  FLGVGAT(ILG), &
        FLGSGAT(ILG),  FLGGGAT(ILG),  HFSCGAT(ILG),  HFSSGAT(ILG), &
        HFSGGAT(ILG),  HEVCGAT(ILG),  HEVSGAT(ILG),  HEVGGAT(ILG), &
        HMFCGAT(ILG),  HMFNGAT(ILG),  HTCCGAT(ILG),  HTCSGAT(ILG), &
        PCFCGAT(ILG),  PCLCGAT(ILG),  PCPNGAT(ILG),  PCPGGAT(ILG), &
        QFGGAT (ILG),  QFNGAT (ILG),  QFCLGAT(ILG),  QFCFGAT(ILG), &
        ROFGAT (ILG),  ROFOGAT(ILG),  ROFSGAT(ILG),  ROFBGAT(ILG), &
        TROFGAT(ILG),  TROOGAT(ILG),  TROSGAT(ILG),  TROBGAT(ILG), &
        ROFCGAT(ILG),  ROFNGAT(ILG),  ROVGGAT(ILG),  WTRCGAT(ILG), &
        WTRSGAT(ILG),  WTRGGAT(ILG),  DRGAT  (ILG)

REAL    HMFGGAT(ILG,IG),  HTCGAT (ILG,IG),  QFCGAT (ILG,IG), &
        GFLXGAT(ILG,IG)
    
! * WATROF DECLARATIONS
REAL    DDGAT(ILG),MANNGAT(ILG)

!     * SAND AND CLAY
REAL    SANDGAT(ILG,IG),   CLAYGAT(ILG,IG)

INTEGER NML,NLTEST,NMTEST,NCOUNT,IMIN,NR2C,NLAT,ILG,XCOUNT,YCOUNT,IC,ICP1,IG
INTEGER XXX(NLAT),YYY(NLAT)
INTEGER ILMOS(ILG),JLMOS(ILG),IGDRGAT(ILG)
INTEGER GRD(NR2C),GAT(NR2C),GRDGAT(NR2C)

REAL    ACLASS(NLTEST,NMTEST+1)
   
INTEGER FILECOUNT,NR2CSTATES
REAL    DATAIN(ILG),DATAOUT(NR2CSTATES,XCOUNT,YCOUNT)

!> INITIALIZE DATA OUTPUT ARRAY
   DATAOUT = 0.0

!> COLLECT OUTPUT DATA
   FILECOUNT = 0

   I = 0
   
!> ATTRIBUTE 1 - 
   DO J = 1, IG
   I = I + 1
   DATAIN = TBARGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO
               
! ATTRIBUTE 2 - 
   DO J = 1, IG
   I = I + 1
   DATAIN = THLQGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO
! ATTRIBUTE 3 -
   DO J = 1, IG
   I = I + 1
   DATAIN = THICGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO
! ATTRIBUTE 4 - 
   I = I + 1
   DATAIN = TPNDGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 5 - 
   I = I + 1
   DATAIN = ZPNDGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 6 - 
   I = I + 1
   DATAIN = TBASGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 7 - 
   I = I + 1
   DATAIN = ALBSGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 8 - 
   I = I + 1
   DATAIN = TSNOGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 9 - 
   I = I + 1
   DATAIN = RHOSGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 10 - 
   I = I + 1
   DATAIN = SNOGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 11 - 
   I = I + 1
   DATAIN = TCANGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 12 - 
   I = I + 1
   DATAIN = RCANGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 13 - 
   I = I + 1
   DATAIN = SCANGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 14 - 
   I = I + 1
   DATAIN = GROGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 15 - 
   I = I + 1
   DATAIN = CMAIGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 16 - 
   DO J = 1, ICP1
   I = I + 1
   DATAIN = FCANGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO
! ATTRIBUTE 17 - 
   DO J = 1, ICP1
   I = I + 1
   DATAIN = LNZ0GAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO
! ATTRIBUTE 18 - 
   DO J = 1, ICP1
   I = I + 1
   DATAIN = ALVCGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO
! ATTRIBUTE 19 - 
   DO J = 1, ICP1
   I = I + 1
   DATAIN = ALICGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO
! ATTRIBUTE 20 - 
   DO J = 1, IC
   I = I + 1
   DATAIN = PAMXGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO
! ATTRIBUTE 21 - 
   DO J = 1, IC
   I = I + 1
   DATAIN = PAMNGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO
! ATTRIBUTE 22 - 
   DO J = 1, IC
   I = I + 1
   DATAIN = CMASGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO
! ATTRIBUTE 23 - 
   DO J = 1, IC
   I = I + 1
   DATAIN = ROOTGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO
! ATTRIBUTE 24 - 
   DO J = 1, IC
   I = I + 1
   DATAIN = RSMNGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO
! ATTRIBUTE 25 - 
   DO J = 1, IC
   I = I + 1
   DATAIN = QA50GAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO
! ATTRIBUTE 26 - 
   DO J = 1, IC
   I = I + 1
   DATAIN = VPDAGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO					 
! ATTRIBUTE 27 - 
   DO J = 1, IC
   I = I + 1
   DATAIN = VPDBGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO
! ATTRIBUTE 28 - 
   DO J = 1, IC
   I = I + 1
   DATAIN = PSGAGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO
! ATTRIBUTE 29 - 
   DO J = 1, IC
   I = I + 1
   DATAIN = PSGBGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO
! ATTRIBUTE 30 - 
   DO J = 1, IC
   I = I + 1
   DATAIN = PAIDGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO
! ATTRIBUTE 31 - 
   DO J = 1, IC
   I = I + 1
   DATAIN = HGTDGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO
! ATTRIBUTE 32 - 
   DO J = 1, IC
   I = I + 1
   DATAIN = ACVDGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO
! ATTRIBUTE 33 - 
   DO J = 1, IC
   I = I + 1
   DATAIN = ACIDGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO
! ATTRIBUTE 34 - 
   DO J = 1, 4
   I = I + 1
   DATAIN = TSFSGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO
! ATTRIBUTE 35 - 
   I = I + 1
   DATAIN = WSNOGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 36 - 
   DO J = 1, IG
   I = I + 1
   DATAIN = THPGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO 
! ATTRIBUTE 37 - 
   DO J = 1, IG
   I = I + 1
   DATAIN = THRGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO 
! ATTRIBUTE 38 - 
   DO J = 1, IG
   I = I + 1
   DATAIN = THMGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO 
! ATTRIBUTE 39 - 
   DO J = 1, IG
   I = I + 1
   DATAIN = BIGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO 
! ATTRIBUTE 40 - 
   DO J = 1, IG
   I = I + 1
   DATAIN = PSISGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO 
! ATTRIBUTE 41 - 
   DO J = 1, IG
   I = I + 1
   DATAIN = GRKSGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO 
! ATTRIBUTE 42 - 
   DO J = 1, IG
   I = I + 1
   DATAIN = THRAGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO 
! ATTRIBUTE 43 - 
   DO J = 1, IG
   I = I + 1
   DATAIN = HCPSGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO 
! ATTRIBUTE 44 - 
   DO J = 1, IG
   I = I + 1
   DATAIN = TCSGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO 
! ATTRIBUTE 45 - 
   DO J = 1, IG
   I = I + 1
   DATAIN = THFCGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO 
! ATTRIBUTE 46 - 
   DO J = 1, IG
   I = I + 1
   DATAIN = PSIWGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO 
! ATTRIBUTE 47 - 
   DO J = 1, IG
   I = I + 1
   DATAIN = DLZWGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO 
! ATTRIBUTE 48 - 
   DO J = 1, IG
   I = I + 1
   DATAIN = ZBTWGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO 
! ATTRIBUTE 49 - 
   I = I + 1
   DATAIN = ZSNLGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 50 - 
   I = I + 1
   DATAIN = ZPLGGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 51 - 
   I = I + 1
   DATAIN = ZPLSGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 52 - 
   I = I + 1
   DATAIN = TACGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 53 - 
   I = I + 1
   DATAIN = QACGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 54 - 
   I = I + 1
   DATAIN = DRNGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 55 - 
   I = I + 1
   DATAIN = XSLPGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 56 - 
   I = I + 1
   DATAIN = XDGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 57 - 
   I = I + 1
   DATAIN = WFSFGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 58 - 
   I = I + 1
   DATAIN = KSGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 59 - 
   I = I + 1
   DATAIN = ALGWGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 60 - 
   I = I + 1
   DATAIN = ALGDGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 61 - 
   I = I + 1
   DATAIN = ASVDGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 62 - 
   I = I + 1
   DATAIN = ASIDGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 63 - 
   I = I + 1
   DATAIN = AGVDGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 64 - 
   I = I + 1
   DATAIN = AGIDGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 65 - 
   DO J = 1, IG
   I = I + 1
   DATAIN = ISNDGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO 
! ATTRIBUTE 66 - 
   I = I + 1
   DATAIN = RADJGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 67 - 
   I = I + 1
   DATAIN = ZBLDGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 68 - 
   I = I + 1
   DATAIN = Z0ORGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 69 - 
   I = I + 1
   DATAIN = ZRFMGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 70 - 
   I = I + 1
   DATAIN = ZRFHGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 71 - 
   I = I + 1
   DATAIN = ZDMGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 72 - 
   I = I + 1
   DATAIN = ZDHGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 73 - 
   I = I + 1
   DATAIN = FSVHGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 74 - 
   I = I + 1
   DATAIN = FSIHGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 75 - 
   I = I + 1
   DATAIN = CSZGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 76 - 
   I = I + 1
   DATAIN = FDLGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 77 - 
   I = I + 1
   DATAIN = ULGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 78 - 
   I = I + 1
   DATAIN = VLGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 79 - 
   I = I + 1
   DATAIN = TAGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 80 - 
   I = I + 1
   DATAIN = QAGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 81 - 
   I = I + 1
   DATAIN = PRESGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 82 - 
   I = I + 1
   DATAIN = PREGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 83 - 
   I = I + 1
   DATAIN = PADRGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 84 - 
   I = I + 1
   DATAIN = VPDGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 85 - 
   I = I + 1
   DATAIN = TADPGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 86 - 
   I = I + 1
   DATAIN = RHOAGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 87 - 
   I = I + 1
   DATAIN = RPCPGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 88 - 
   I = I + 1
   DATAIN = TRPCGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 89 - 
   I = I + 1
   DATAIN = SPCPGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 90 - 
   I = I + 1
   DATAIN = TSPCGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 91 - 
   I = I + 1
   DATAIN = RHSIGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 92 - 
   I = I + 1
   DATAIN = FCLOGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 93 - 
   I = I + 1
   DATAIN = DLONGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 94 - 
   I = I + 1
   DATAIN = GGEOGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 95 - 
   I = I + 1
   DATAIN = CDHGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 96 - 
   I = I + 1
   DATAIN = CDMGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 97 - 
   I = I + 1
   DATAIN = HFSGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 98 - 
   I = I + 1
   DATAIN = TFXGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 99 - 
   I = I + 1
   DATAIN = QEVPGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 100 - 
   I = I + 1
   DATAIN = QFSGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 101 - 
   I = I + 1
   DATAIN = QFXGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 102 - 
   I = I + 1
   DATAIN = PETGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 103 - 
   I = I + 1
   DATAIN = GAGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 104 - 
   I = I + 1
   DATAIN = EFGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 105 - 
   I = I + 1
   DATAIN = GTGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 106 - 
   I = I + 1
   DATAIN = QGGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)

! ATTRIBUTE 107 - 
   I = I + 1
   DATAIN = ALVSGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 108 - 
   I = I + 1
   DATAIN = ALIRGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 109 - 
   I = I + 1
   DATAIN = SFCTGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 110 - 
   I = I + 1
   DATAIN = SFCUGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 111 - 
   I = I + 1
   DATAIN = SFCVGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 112 - 
   I = I + 1
   DATAIN = SFCQGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 113 - 
   I = I + 1
   DATAIN = FSNOGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 114 - 
   I = I + 1
   DATAIN = FSGVGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 115 - 
   I = I + 1
   DATAIN = FSGSGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 116 - 
   I = I + 1
   DATAIN = FSGGGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 117 - 
   I = I + 1
   DATAIN = FLGVGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 118 - 
   I = I + 1
   DATAIN = FLGSGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 119 - 
   I = I + 1
   DATAIN = FLGGGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 120 - 
   I = I + 1
   DATAIN = HFSCGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 121 - 
   I = I + 1
   DATAIN = HFSSGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 122 - 
   I = I + 1
   DATAIN = HFSGGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 123 - 
   I = I + 1
   DATAIN = HEVCGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 124 - 
   I = I + 1
   DATAIN = HEVSGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 125 - 
   I = I + 1
   DATAIN = HEVGGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 126 - 
   I = I + 1
   DATAIN = HMFCGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 127 - 
   I = I + 1
   DATAIN = HMFNGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 128 - 
   I = I + 1
   DATAIN = HTCCGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 129 - 
   I = I + 1
   DATAIN = HTCSGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 130 - 
   I = I + 1
   DATAIN = PCFCGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 131 - 
   I = I + 1
   DATAIN = PCLCGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 132 - 
   I = I + 1
   DATAIN = PCPNGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 133 - 
   I = I + 1
   DATAIN = PCPGGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 134 - 
   I = I + 1
   DATAIN = QFGGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 135 - 
   I = I + 1
   DATAIN = QFNGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 136 - 
   I = I + 1
   DATAIN = QFCLGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 137 - 
   I = I + 1
   DATAIN = QFCFGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 138 - 
   I = I + 1
   DATAIN = ROFGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 139 - 
   I = I + 1
   DATAIN = ROFOGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 140 - 
   I = I + 1
   DATAIN = ROFSGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 141 - 
   I = I + 1
   DATAIN = ROFBGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 142 - 
   I = I + 1
   DATAIN = TROFGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 143 - 
   I = I + 1
   DATAIN = TROOGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 144 - 
   I = I + 1
   DATAIN = TROSGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 145 - 
   I = I + 1
   DATAIN = TROBGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 146 - 
   I = I + 1
   DATAIN = ROFCGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 147 - 
   I = I + 1
   DATAIN = ROFNGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 148 - 
   I = I + 1
   DATAIN = ROVGGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 149 - 
   I = I + 1
   DATAIN = WTRCGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 150 - 
   I = I + 1
   DATAIN = WTRSGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 151 - 
   I = I + 1
   DATAIN = WTRGGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 152 - 
   I = I + 1
   DATAIN = DRGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 153 - 
   DO J = 1, IG
   I = I + 1
   DATAIN = GFLXGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO 

! ATTRIBUTE 154 - 
   DO J = 1, IG
   I = I + 1
   DATAIN = HMFGGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO 
! ATTRIBUTE 155 - 
   DO J = 1, IG
   I = I + 1
   DATAIN = HTCGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO 
   
! ATTRIBUTE 156 - 
   DO J = 1, IG
   I = I + 1
   DATAIN = QFCGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO 
   
! ATTRIBUTE 157 - 
   I = I + 1
   DATAIN = MANNGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
! ATTRIBUTE 158 - 
   I = I + 1
   DATAIN = DDGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)

!> ATTRIBUTE 159 - 
   DO J = 1, IG
   I = I + 1
   DATAIN = SANDGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO
               
!> ATTRIBUTE 160 - 
   DO J = 1, IG
   I = I + 1
   DATAIN = CLAYGAT(:,J)
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO
               
!> ATTRIBUTE 161 - 
   I = I + 1
   DATAIN = IGDRGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)           

!> ATTRIBUTE 162 - 
   I = I + 1
   DATAIN = VMODGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)

!> ATTRIBUTE 163 - 
   I = I + 1
   DATAIN = QLWOGAT
   CALL COLLECTDATA(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   
RETURN

END

SUBROUTINE COLLECTDATA(DATAIN,DATAOUT,GRD,GAT,GRDGAT,FILECOUNT,NLAT,NR2CSTATES, &
                       NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                       ACLASS)

INTEGER GRD,GAT,GRDGAT,FILECOUNT,NLAT,NR2CSTATES,NLTEST,NMTEST,NML,ILG,XCOUNT,YCOUNT
INTEGER XXX(NLAT),YYY(NLAT),ILMOS(ILG),JLMOS(ILG)
REAL    ACLASS(NLTEST,NMTEST+1),DATAIN(ILG),DATAOUT(NR2CSTATES,XCOUNT,YCOUNT), &
        DATAOUTTMP(NMTEST,XCOUNT,YCOUNT)

   IF(GRD == 1)THEN
      FILECOUNT = FILECOUNT + 1
      DO I = 1, NML
         II = XXX(ILMOS(I))
         JJ = YYY(ILMOS(I))
         DATAOUT(FILECOUNT,II,JJ) = DATAOUT(FILECOUNT,II,JJ) + DATAIN(I) * ACLASS(ILMOS(I),JLMOS(I))
      END DO
   ENDIF
   
   DATAOUTTMP = 0.0
   IF(GAT == 1)THEN
      DO I = 1, NML
         II = XXX(ILMOS(I))
         JJ = YYY(ILMOS(I))
         DATAOUTTMP(JLMOS(I),II,JJ) = DATAIN(I)
      END DO
      DO J = 1, NMTEST
         FILECOUNT = FILECOUNT + 1
         DATAOUT(FILECOUNT,:,:) = DATAOUTTMP(J,:,:)
      ENDDO
   ENDIF
   
   DATAOUTTMP = 0.0
   IF(GRDGAT == 1)THEN
      DO I = 1, NML
         II = XXX(ILMOS(I))
         JJ = YYY(ILMOS(I))
         DATAOUTTMP(JLMOS(I),II,JJ) = DATAIN(I) * ACLASS(ILMOS(I),JLMOS(I))
      END DO
      DO J = 1, NMTEST
         FILECOUNT = FILECOUNT + 1
         DATAOUT(FILECOUNT,:,:) = DATAOUTTMP(J,:,:)
      ENDDO
   ENDIF
RETURN
END